package com.gravapr.gravaprserver.enums;

public enum Lift {
    BACKSQUAT,
    FRONTSQUAT,
    CLEAN,
    SQUATCLEAN,
    POWERCLEAN,
    MUSCLECLEAN,
    SNATCH,
    SQUATSNATCH,
    POWERSNATCH,
    MUSCLESNATCH,
    SNATCHBALANCE,
    SHOULDERPRESS,
    PUSHPRESS,
    PUSHJERK,
    SPLITJERK,
    CLEANANDJERK
}
